"""adiciona tabela de midias enviadas

Revision ID: f0bd4a822918
Revises: 1b9f208ac393
Create Date: 2026-07-21 01:07:06.483767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bd4a822918'
down_revision = '1b9f208ac393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_uuid'))
        batch_op.drop_index(batch_op.f('ix_media_assets_kind'))
        batch_op.drop_index(batch_op.f('ix_media_assets_document_id'))
        batch_op.drop_index(batch_op.f('ix_media_assets_created_at'))

    op.drop_table('media_assets')
    # ### end Alembic commands ###
